theme: jekyll-theme-midnight

title: TheEpicCowOfLife's Blog
author: Quang Ong
email: TheEpicCowOfLife@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Imagine reviving this blog, couldn't be me.
# social links
twitter_username: haha lol
github_username:  your-github-handle

show_excerpts: false # set to false to remove excerpts on the homepage

# Use the following plug-ins
#plugins:
#        - jekyll-sitemap # Create a sitemap
#        - jekyll-feed # Create an Atom feed
